// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp.API.Data;

#nullable disable

namespace WebApp.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DaiLyDonVi", b =>
                {
                    b.Property<int>("DaiLysId")
                        .HasColumnType("integer");

                    b.Property<int>("DonVisId")
                        .HasColumnType("integer");

                    b.HasKey("DaiLysId", "DonVisId");

                    b.HasIndex("DonVisId");

                    b.ToTable("DaiLyDonVi");
                });

            modelBuilder.Entity("WebApp.API.Models.BienLai", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("ghi_chu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("is_bhxh")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_bhyt")
                        .HasColumnType("boolean");

                    b.Property<int>("ke_khai_bhyt_id")
                        .HasColumnType("integer");

                    b.Property<string>("ma_co_quan_bhxh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ma_nhan_vien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ma_so_bhxh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ma_so_bhxh_don_vi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("ngay_bien_lai")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("quyen_so")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("so_bien_lai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("so_tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ten_nguoi_dong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("tinh_chat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id");

                    b.HasIndex("ke_khai_bhyt_id")
                        .IsUnique();

                    b.ToTable("bien_lai", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.BienlaiDienTu.BienLaiDienTu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("ghi_chu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("is_bhxh")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_bhyt")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_published_to_vnpt")
                        .HasColumnType("boolean");

                    b.Property<int?>("ke_khai_bhyt_id")
                        .HasColumnType("integer");

                    b.Property<string>("ky_hieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ma_co_quan_bhxh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ma_nhan_vien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ma_so_bhxh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ma_so_bhxh_don_vi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("ngay_bien_lai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ngay_tao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("quyen_bien_lai_dien_tu_id")
                        .HasColumnType("integer");

                    b.Property<string>("so_bien_lai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("so_tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ten_nguoi_dong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("tinh_chat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("vnpt_invoice_no")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("vnpt_key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("vnpt_pattern")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("vnpt_publish_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("vnpt_response")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("vnpt_serial")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id");

                    b.HasIndex("ke_khai_bhyt_id");

                    b.HasIndex("quyen_bien_lai_dien_tu_id");

                    b.ToTable("bien_lai_dien_tu", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.BienlaiDienTu.QuyenBienLaiDienTu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("den_so")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ky_hieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ma_co_quan_bhxh")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ngay_cap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("nguoi_cap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("so_hien_tai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("tu_so")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id");

                    b.ToTable("quyen_bien_lai_dien_tu", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.DanhMucCSKCB", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ma_tinh_kcb")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ma_tinh_kcb");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("id");

                    b.ToTable("dm_cskcb", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.DanhMucHuyen", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ma_tinh")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ma_tinh");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("ma")
                        .IsUnique();

                    b.HasIndex("ma_tinh");

                    b.ToTable("ds_huyen", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.DanhMucTinh", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.ToTable("ds_tinh");
                });

            modelBuilder.Entity("WebApp.API.Models.DanhMucXa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("ma_huyen")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("ma_huyen");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("ma")
                        .IsUnique();

                    b.HasIndex("ma_huyen");

                    b.ToTable("ds_xa", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.DonVi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DmKhoiKcbId")
                        .HasColumnType("integer")
                        .HasColumnName("dm_khoi_kcb_id");

                    b.Property<bool>("IsBHXHTN")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bhxhtn");

                    b.Property<bool>("IsBHYT")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bhyt");

                    b.Property<string>("MaCoQuanBHXH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ma_co_quan_bhxh");

                    b.Property<string>("MaSoBHXH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ma_so_bhxh");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ten_don_vi");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("trang_thai");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("don_vi", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.DotKeKhai", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("dai_ly_id")
                        .HasColumnType("integer")
                        .HasColumnName("dai_ly_id");

                    b.Property<string>("dich_vu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("don_vi_id")
                        .HasColumnType("integer")
                        .HasColumnName("don_vi_id");

                    b.Property<string>("ghi_chu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("is_bien_lai_dien_tu")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bien_lai_dien_tu");

                    b.Property<string>("ma_ho_so")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ma_ho_so");

                    b.Property<int>("nam")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ngay_gui")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_gui");

                    b.Property<DateTime>("ngay_tao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("so_dot")
                        .HasColumnType("integer");

                    b.Property<string>("ten_dot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("thang")
                        .HasColumnType("integer");

                    b.Property<int?>("tong_so_the")
                        .HasColumnType("integer")
                        .HasColumnName("tong_so_the");

                    b.Property<decimal?>("tong_so_tien")
                        .HasColumnType("numeric")
                        .HasColumnName("tong_so_tien");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("chua_gui");

                    b.Property<string>("url_bill")
                        .HasColumnType("text")
                        .HasColumnName("url_bill");

                    b.HasKey("id");

                    b.HasIndex("dai_ly_id");

                    b.HasIndex("don_vi_id");

                    b.ToTable("dot_ke_khai", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.HoaDonThanhToan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by");

                    b.Property<int>("dot_ke_khai_id")
                        .HasColumnType("integer")
                        .HasColumnName("dot_ke_khai_id");

                    b.Property<string>("ghi_chu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime>("ngay_tao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ngay_thanh_toan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_thanh_toan")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("noi_dung_thanh_toan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("noi_dung_thanh_toan");

                    b.Property<string>("public_id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_id");

                    b.Property<decimal>("so_tien")
                        .HasColumnType("numeric")
                        .HasColumnName("so_tien");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("cho_duyet")
                        .HasColumnName("trang_thai");

                    b.Property<string>("url_bill")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_bill");

                    b.HasKey("id");

                    b.HasIndex("dot_ke_khai_id");

                    b.ToTable("hoa_don_thanh_toan", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.KeKhaiBHXH", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("dot_ke_khai_id")
                        .HasColumnType("integer")
                        .HasColumnName("dot_ke_khai_id");

                    b.Property<string>("ghi_chu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("huyen_nkq")
                        .HasColumnType("text")
                        .HasColumnName("huyen_nkq");

                    b.Property<bool>("is_urgent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_urgent");

                    b.Property<string>("loai_khai_bao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loai_khai_bao");

                    b.Property<string>("loai_nsnn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loai_nsnn");

                    b.Property<string>("ma_ho_so")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ma_ho_so");

                    b.Property<string>("ma_nhan_vien")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ma_nhan_vien");

                    b.Property<decimal>("muc_thu_nhap")
                        .HasColumnType("numeric")
                        .HasColumnName("muc_thu_nhap");

                    b.Property<DateTime?>("ngay_bien_lai")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_bien_lai");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("phuong_an")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phuong_an");

                    b.Property<int>("phuong_thuc_dong")
                        .HasColumnType("integer")
                        .HasColumnName("phuong_thuc_dong");

                    b.Property<int?>("quyen_bien_lai_id")
                        .HasColumnType("integer")
                        .HasColumnName("quyen_bien_lai_id");

                    b.Property<string>("so_bien_lai")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("so_bien_lai");

                    b.Property<int>("so_thang_dong")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("so_thang_dong");

                    b.Property<decimal>("so_tien_can_dong")
                        .HasColumnType("numeric")
                        .HasColumnName("so_tien_can_dong");

                    b.Property<string>("thang_bat_dau")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thang_bat_dau");

                    b.Property<int>("thong_tin_the_id")
                        .HasColumnType("integer")
                        .HasColumnName("thong_tin_the_id");

                    b.Property<decimal>("tien_ho_tro")
                        .HasColumnType("numeric")
                        .HasColumnName("tien_ho_tro");

                    b.Property<string>("tinh_nkq")
                        .HasColumnType("text")
                        .HasColumnName("tinh_nkq");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trang_thai");

                    b.Property<decimal>("ty_le_dong")
                        .HasColumnType("numeric")
                        .HasColumnName("ty_le_dong");

                    b.Property<decimal?>("ty_le_nsnn")
                        .HasColumnType("numeric")
                        .HasColumnName("ty_le_nsnn");

                    b.Property<string>("xa_nkq")
                        .HasColumnType("text")
                        .HasColumnName("xa_nkq");

                    b.HasKey("id");

                    b.HasIndex("dot_ke_khai_id");

                    b.HasIndex("thong_tin_the_id");

                    b.ToTable("ke_khai_bhxh");
                });

            modelBuilder.Entity("WebApp.API.Models.KeKhaiBHYT", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("benh_vien_kcb")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("dia_chi_nkq")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("dot_ke_khai_id")
                        .HasColumnType("integer")
                        .HasColumnName("dot_ke_khai_id");

                    b.Property<DateTime?>("han_the_cu")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("han_the_moi_den")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("han_the_moi_tu")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("huyen_nkq")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("is_urgent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_urgent");

                    b.Property<string>("ma_ho_so")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ngay_bien_lai")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ngay_tao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("nguoi_thu")
                        .HasColumnType("integer");

                    b.Property<string>("phuong_an_dong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("quyen_bien_lai_id")
                        .HasColumnType("integer");

                    b.Property<string>("so_bien_lai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("so_thang_dong")
                        .HasColumnType("integer");

                    b.Property<decimal>("so_tien_can_dong")
                        .HasColumnType("numeric")
                        .HasColumnName("so_tien_can_dong");

                    b.Property<int>("thong_tin_the_id")
                        .HasColumnType("integer");

                    b.Property<string>("tinh_nkq")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.Property<string>("xa_nkq")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id");

                    b.HasIndex("dot_ke_khai_id");

                    b.HasIndex("quyen_bien_lai_id");

                    b.HasIndex("thong_tin_the_id");

                    b.ToTable("ke_khai_bhyt", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.NguoiDung", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("chuc_danh")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("client_id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("don_vi_cong_tac")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ho_ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("is_super_admin")
                        .HasColumnType("boolean");

                    b.Property<string>("ma_nhan_vien")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string[]>("roles")
                        .HasColumnType("text[]");

                    b.Property<string>("so_dien_thoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int?>("type_mang_luoi")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.HasIndex("user_name")
                        .IsUnique();

                    b.ToTable("nguoi_dung", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.PaymentBill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("batch_id")
                        .HasColumnType("integer");

                    b.Property<string>("cloudinary_public_id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("file_url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("uploaded_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("uploaded_by")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("uploaded_by");

                    b.ToTable("payment_bills", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.QuyenBienLai", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("den_so")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ngay_cap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("nguoi_cap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("nhan_vien_thu")
                        .HasColumnType("integer")
                        .HasColumnName("nhan_vien_thu");

                    b.Property<string>("quyen_so")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("so_hien_tai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("tu_so")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id");

                    b.HasIndex("nhan_vien_thu");

                    b.ToTable("quyen_bien_lai", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.ThongTinThe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("cccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("gioi_tinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ho_ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ma_benh_vien")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ma_dan_toc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ma_hgd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ma_huyen_ks")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ma_huyen_nkq")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ma_so_bhxh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ma_tinh_ks")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ma_tinh_nkq")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ma_xa_ks")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ma_xa_nkq")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ngay_sinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ngay_tao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("quoc_tich")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("so_dien_thoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("so_the_bhyt")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("id");

                    b.HasIndex("cccd")
                        .IsUnique();

                    b.HasIndex("ma_so_bhxh")
                        .IsUnique();

                    b.ToTable("thong_tin_the", (string)null);
                });

            modelBuilder.Entity("WebApp.API.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("commune")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("department_code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("district")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("first_login")
                        .HasColumnType("boolean");

                    b.Property<string>("hamlet")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ho_ten")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("last_login_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("last_login_ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("last_login_location")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("password_changed")
                        .HasColumnType("boolean");

                    b.Property<string>("province")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("role")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("so_dien_thoai")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active");

                    b.Property<string>("unit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("unit_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WebApp.Server.Models.DaiLy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ma");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NguoiDaiDien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nguoi_dai_dien");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("dai_ly", (string)null);
                });

            modelBuilder.Entity("WebApp.Server.Models.DaiLyDonVi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DaiLyId")
                        .HasColumnType("integer")
                        .HasColumnName("dai_ly_id");

                    b.Property<int>("DonViId")
                        .HasColumnType("integer")
                        .HasColumnName("don_vi_id");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nguoi_tao");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("DaiLyId");

                    b.HasIndex("DonViId");

                    b.ToTable("dai_ly_don_vi");
                });

            modelBuilder.Entity("DaiLyDonVi", b =>
                {
                    b.HasOne("WebApp.Server.Models.DaiLy", null)
                        .WithMany()
                        .HasForeignKey("DaiLysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.API.Models.DonVi", null)
                        .WithMany()
                        .HasForeignKey("DonVisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.API.Models.BienLai", b =>
                {
                    b.HasOne("WebApp.API.Models.KeKhaiBHYT", "KeKhaiBHYT")
                        .WithOne("BienLai")
                        .HasForeignKey("WebApp.API.Models.BienLai", "ke_khai_bhyt_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeKhaiBHYT");
                });

            modelBuilder.Entity("WebApp.API.Models.BienlaiDienTu.BienLaiDienTu", b =>
                {
                    b.HasOne("WebApp.API.Models.KeKhaiBHYT", "KeKhaiBHYT")
                        .WithMany()
                        .HasForeignKey("ke_khai_bhyt_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApp.API.Models.BienlaiDienTu.QuyenBienLaiDienTu", "QuyenBienLaiDienTu")
                        .WithMany()
                        .HasForeignKey("quyen_bien_lai_dien_tu_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KeKhaiBHYT");

                    b.Navigation("QuyenBienLaiDienTu");
                });

            modelBuilder.Entity("WebApp.API.Models.DanhMucHuyen", b =>
                {
                    b.HasOne("WebApp.API.Models.DanhMucTinh", null)
                        .WithMany()
                        .HasForeignKey("ma_tinh")
                        .HasPrincipalKey("ma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.API.Models.DanhMucXa", b =>
                {
                    b.HasOne("WebApp.API.Models.DanhMucHuyen", null)
                        .WithMany()
                        .HasForeignKey("ma_huyen")
                        .HasPrincipalKey("ma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.API.Models.DotKeKhai", b =>
                {
                    b.HasOne("WebApp.Server.Models.DaiLy", "DaiLy")
                        .WithMany()
                        .HasForeignKey("dai_ly_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.API.Models.DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("don_vi_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DaiLy");

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("WebApp.API.Models.HoaDonThanhToan", b =>
                {
                    b.HasOne("WebApp.API.Models.DotKeKhai", "DotKeKhai")
                        .WithMany()
                        .HasForeignKey("dot_ke_khai_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DotKeKhai");
                });

            modelBuilder.Entity("WebApp.API.Models.KeKhaiBHXH", b =>
                {
                    b.HasOne("WebApp.API.Models.DotKeKhai", "DotKeKhai")
                        .WithMany()
                        .HasForeignKey("dot_ke_khai_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.API.Models.ThongTinThe", "ThongTinThe")
                        .WithMany()
                        .HasForeignKey("thong_tin_the_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DotKeKhai");

                    b.Navigation("ThongTinThe");
                });

            modelBuilder.Entity("WebApp.API.Models.KeKhaiBHYT", b =>
                {
                    b.HasOne("WebApp.API.Models.DotKeKhai", "DotKeKhai")
                        .WithMany("KeKhaiBHYTs")
                        .HasForeignKey("dot_ke_khai_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KeKhaiBHYT_DotKeKhai");

                    b.HasOne("WebApp.API.Models.QuyenBienLai", "QuyenBienLai")
                        .WithMany()
                        .HasForeignKey("quyen_bien_lai_id");

                    b.HasOne("WebApp.API.Models.ThongTinThe", "ThongTinThe")
                        .WithMany()
                        .HasForeignKey("thong_tin_the_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DotKeKhai");

                    b.Navigation("QuyenBienLai");

                    b.Navigation("ThongTinThe");
                });

            modelBuilder.Entity("WebApp.API.Models.PaymentBill", b =>
                {
                    b.HasOne("WebApp.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("uploaded_by")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApp.API.Models.QuyenBienLai", b =>
                {
                    b.HasOne("WebApp.API.Models.NguoiDung", "NguoiThu")
                        .WithMany()
                        .HasForeignKey("nhan_vien_thu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiThu");
                });

            modelBuilder.Entity("WebApp.Server.Models.DaiLyDonVi", b =>
                {
                    b.HasOne("WebApp.Server.Models.DaiLy", "DaiLy")
                        .WithMany()
                        .HasForeignKey("DaiLyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.API.Models.DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaiLy");

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("WebApp.API.Models.DotKeKhai", b =>
                {
                    b.Navigation("KeKhaiBHYTs");
                });

            modelBuilder.Entity("WebApp.API.Models.KeKhaiBHYT", b =>
                {
                    b.Navigation("BienLai");
                });
#pragma warning restore 612, 618
        }
    }
}
